on: push
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
       - name: checkout
         uses: actions/checkout@v4

       - name: Yandex Cloud CR "Login" Action for GitHub Actions
         id: login-cr
         uses: yc-actions/yc-cr-login@v2.0.0
         with:
          yc-sa-id: ${{ secrets.YC_SA_ID }}

       - name: Build, tag, and push image to Yandex Cloud Container Registry
         env:
          CR_REGISTRY: crpimvecm0b86e4qccrt
          CR_REPOSITORY: my-cr-repo
          IMAGE_TAG: ${{ github.sha }}
         run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
